services:
    app:
        container_name: canoe-app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - canoe-net
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        container_name: canoe-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - canoe-net
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: canoe-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: canoe
            MYSQL_USER: canoe
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - canoe-net

volumes:
    mysql-data:

networks:
    canoe-net:
